/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamCode = IDL.Text;
export const SessionId = IDL.Nat;
export const CityQuestion = IDL.Record({
  'id' : IDL.Nat,
  'gambar1' : IDL.Text,
  'gambar2' : IDL.Text,
  'poinDasar' : IDL.Nat,
  'batasWaktu' : IDL.Nat,
  'pilihan' : IDL.Vec(IDL.Text),
  'namaKota' : IDL.Text,
  'penjelasan' : IDL.Text,
});
export const UserId = IDL.Principal;
export const EntriLeaderboard = IDL.Record({
  'namaPemain' : IDL.Text,
  'userId' : UserId,
  'totalPoin' : IDL.Nat,
  'namaTim' : IDL.Opt(IDL.Text),
  'jumlahPermainan' : IDL.Nat,
});
export const PuzzleId = IDL.Nat;
export const Difficulty = IDL.Variant({
  'mudah' : IDL.Null,
  'sedang' : IDL.Null,
  'sulit' : IDL.Null,
});
export const Puzzle = IDL.Record({
  'id' : PuzzleId,
  'pertanyaan' : IDL.Text,
  'jawabanBenar' : IDL.Nat,
  'poinDasar' : IDL.Nat,
  'batasWaktu' : IDL.Nat,
  'pilihan' : IDL.Vec(IDL.Text),
  'kesulitan' : Difficulty,
  'penjelasan' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const RiwayatSesi = IDL.Record({
  'akurasi' : IDL.Nat,
  'tanggal' : Timestamp,
  'mode' : IDL.Text,
  'poin' : IDL.Nat,
  'sessionId' : SessionId,
});
export const StatusSesi = IDL.Variant({
  'aktif' : IDL.Null,
  'selesai' : IDL.Null,
});
export const ModeSesi = IDL.Variant({ 'tim' : IDL.Null, 'solo' : IDL.Null });
export const JawabanAnggota = IDL.Record({
  'userId' : UserId,
  'poinDiperoleh' : IDL.Nat,
  'pilihanJawaban' : IDL.Nat,
  'waktuSubmit' : Timestamp,
  'benar' : IDL.Bool,
});
export const JawabanPuzzle = IDL.Record({
  'sudahDievaluasi' : IDL.Bool,
  'poinTim' : IDL.Nat,
  'puzzleId' : PuzzleId,
  'waktuMulai' : Timestamp,
  'jawabanAnggota' : IDL.Vec(JawabanAnggota),
});
export const Sesi = IDL.Record({
  'id' : SessionId,
  'status' : StatusSesi,
  'kodeJoin' : IDL.Opt(IDL.Text),
  'mode' : ModeSesi,
  'anggota' : IDL.Vec(UserId),
  'totalPoin' : IDL.Nat,
  'waktuMulai' : Timestamp,
  'puzzles' : IDL.Vec(PuzzleId),
  'indeksPuzzleAktif' : IDL.Nat,
  'namaTim' : IDL.Opt(IDL.Text),
  'waktuSelesai' : IDL.Opt(Timestamp),
  'jawabanPuzzles' : IDL.Vec(JawabanPuzzle),
});
export const HasilJawaban = IDL.Record({
  'poinTim' : IDL.Opt(IDL.Nat),
  'poinDiperoleh' : IDL.Nat,
  'semuaSudahJawab' : IDL.Bool,
  'benar' : IDL.Bool,
  'penjelasan' : IDL.Text,
});

export const idlService = IDL.Service({
  'bergabungSesiTim' : IDL.Func([TeamCode], [IDL.Opt(SessionId)], []),
  'buatSesiSolo' : IDL.Func([], [SessionId], []),
  'buatSesiTim' : IDL.Func([], [SessionId, TeamCode], []),
  'daftarkanNama' : IDL.Func([IDL.Text, SessionId, IDL.Opt(IDL.Text)], [], []),
  'getCityQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(CityQuestion)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(EntriLeaderboard)], ['query']),
  'getPoinKumulatif' : IDL.Func([], [IDL.Nat], ['query']),
  'getPoinSesi' : IDL.Func([SessionId], [IDL.Nat], ['query']),
  'getPuzzle' : IDL.Func([PuzzleId], [IDL.Opt(Puzzle)], ['query']),
  'getRiwayatSesi' : IDL.Func([], [IDL.Vec(RiwayatSesi)], ['query']),
  'getSesi' : IDL.Func([SessionId], [IDL.Opt(Sesi)], ['query']),
  'puzzleByKesulitan' : IDL.Func([Difficulty], [IDL.Vec(Puzzle)], ['query']),
  'semuaCityQuestions' : IDL.Func([], [IDL.Vec(CityQuestion)], ['query']),
  'semuaPuzzle' : IDL.Func([], [IDL.Vec(Puzzle)], ['query']),
  'setNamaTim' : IDL.Func([SessionId, IDL.Text], [IDL.Bool], []),
  'submitJawaban' : IDL.Func(
      [SessionId, PuzzleId, IDL.Nat],
      [HasilJawaban],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamCode = IDL.Text;
  const SessionId = IDL.Nat;
  const CityQuestion = IDL.Record({
    'id' : IDL.Nat,
    'gambar1' : IDL.Text,
    'gambar2' : IDL.Text,
    'poinDasar' : IDL.Nat,
    'batasWaktu' : IDL.Nat,
    'pilihan' : IDL.Vec(IDL.Text),
    'namaKota' : IDL.Text,
    'penjelasan' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const EntriLeaderboard = IDL.Record({
    'namaPemain' : IDL.Text,
    'userId' : UserId,
    'totalPoin' : IDL.Nat,
    'namaTim' : IDL.Opt(IDL.Text),
    'jumlahPermainan' : IDL.Nat,
  });
  const PuzzleId = IDL.Nat;
  const Difficulty = IDL.Variant({
    'mudah' : IDL.Null,
    'sedang' : IDL.Null,
    'sulit' : IDL.Null,
  });
  const Puzzle = IDL.Record({
    'id' : PuzzleId,
    'pertanyaan' : IDL.Text,
    'jawabanBenar' : IDL.Nat,
    'poinDasar' : IDL.Nat,
    'batasWaktu' : IDL.Nat,
    'pilihan' : IDL.Vec(IDL.Text),
    'kesulitan' : Difficulty,
    'penjelasan' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const RiwayatSesi = IDL.Record({
    'akurasi' : IDL.Nat,
    'tanggal' : Timestamp,
    'mode' : IDL.Text,
    'poin' : IDL.Nat,
    'sessionId' : SessionId,
  });
  const StatusSesi = IDL.Variant({ 'aktif' : IDL.Null, 'selesai' : IDL.Null });
  const ModeSesi = IDL.Variant({ 'tim' : IDL.Null, 'solo' : IDL.Null });
  const JawabanAnggota = IDL.Record({
    'userId' : UserId,
    'poinDiperoleh' : IDL.Nat,
    'pilihanJawaban' : IDL.Nat,
    'waktuSubmit' : Timestamp,
    'benar' : IDL.Bool,
  });
  const JawabanPuzzle = IDL.Record({
    'sudahDievaluasi' : IDL.Bool,
    'poinTim' : IDL.Nat,
    'puzzleId' : PuzzleId,
    'waktuMulai' : Timestamp,
    'jawabanAnggota' : IDL.Vec(JawabanAnggota),
  });
  const Sesi = IDL.Record({
    'id' : SessionId,
    'status' : StatusSesi,
    'kodeJoin' : IDL.Opt(IDL.Text),
    'mode' : ModeSesi,
    'anggota' : IDL.Vec(UserId),
    'totalPoin' : IDL.Nat,
    'waktuMulai' : Timestamp,
    'puzzles' : IDL.Vec(PuzzleId),
    'indeksPuzzleAktif' : IDL.Nat,
    'namaTim' : IDL.Opt(IDL.Text),
    'waktuSelesai' : IDL.Opt(Timestamp),
    'jawabanPuzzles' : IDL.Vec(JawabanPuzzle),
  });
  const HasilJawaban = IDL.Record({
    'poinTim' : IDL.Opt(IDL.Nat),
    'poinDiperoleh' : IDL.Nat,
    'semuaSudahJawab' : IDL.Bool,
    'benar' : IDL.Bool,
    'penjelasan' : IDL.Text,
  });
  
  return IDL.Service({
    'bergabungSesiTim' : IDL.Func([TeamCode], [IDL.Opt(SessionId)], []),
    'buatSesiSolo' : IDL.Func([], [SessionId], []),
    'buatSesiTim' : IDL.Func([], [SessionId, TeamCode], []),
    'daftarkanNama' : IDL.Func(
        [IDL.Text, SessionId, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getCityQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(CityQuestion)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(EntriLeaderboard)], ['query']),
    'getPoinKumulatif' : IDL.Func([], [IDL.Nat], ['query']),
    'getPoinSesi' : IDL.Func([SessionId], [IDL.Nat], ['query']),
    'getPuzzle' : IDL.Func([PuzzleId], [IDL.Opt(Puzzle)], ['query']),
    'getRiwayatSesi' : IDL.Func([], [IDL.Vec(RiwayatSesi)], ['query']),
    'getSesi' : IDL.Func([SessionId], [IDL.Opt(Sesi)], ['query']),
    'puzzleByKesulitan' : IDL.Func([Difficulty], [IDL.Vec(Puzzle)], ['query']),
    'semuaCityQuestions' : IDL.Func([], [IDL.Vec(CityQuestion)], ['query']),
    'semuaPuzzle' : IDL.Func([], [IDL.Vec(Puzzle)], ['query']),
    'setNamaTim' : IDL.Func([SessionId, IDL.Text], [IDL.Bool], []),
    'submitJawaban' : IDL.Func(
        [SessionId, PuzzleId, IDL.Nat],
        [HasilJawaban],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };