/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CityQuestion {
  'id' : bigint,
  'gambar1' : string,
  'gambar2' : string,
  'poinDasar' : bigint,
  'batasWaktu' : bigint,
  'pilihan' : Array<string>,
  'namaKota' : string,
  'penjelasan' : string,
}
export type Difficulty = { 'mudah' : null } |
  { 'sedang' : null } |
  { 'sulit' : null };
export interface EntriLeaderboard {
  'namaPemain' : string,
  'userId' : UserId,
  'totalPoin' : bigint,
  'namaTim' : [] | [string],
  'jumlahPermainan' : bigint,
}
export interface HasilJawaban {
  'poinTim' : [] | [bigint],
  'poinDiperoleh' : bigint,
  'semuaSudahJawab' : boolean,
  'benar' : boolean,
  'penjelasan' : string,
}
export interface JawabanAnggota {
  'userId' : UserId,
  'poinDiperoleh' : bigint,
  'pilihanJawaban' : bigint,
  'waktuSubmit' : Timestamp,
  'benar' : boolean,
}
export interface JawabanPuzzle {
  'sudahDievaluasi' : boolean,
  'poinTim' : bigint,
  'puzzleId' : PuzzleId,
  'waktuMulai' : Timestamp,
  'jawabanAnggota' : Array<JawabanAnggota>,
}
export type ModeSesi = { 'tim' : null } |
  { 'solo' : null };
export interface Puzzle {
  'id' : PuzzleId,
  'pertanyaan' : string,
  'jawabanBenar' : bigint,
  'poinDasar' : bigint,
  'batasWaktu' : bigint,
  'pilihan' : Array<string>,
  'kesulitan' : Difficulty,
  'penjelasan' : string,
}
export type PuzzleId = bigint;
export interface RiwayatSesi {
  'akurasi' : bigint,
  'tanggal' : Timestamp,
  'mode' : string,
  'poin' : bigint,
  'sessionId' : SessionId,
}
export interface Sesi {
  'id' : SessionId,
  'status' : StatusSesi,
  'kodeJoin' : [] | [string],
  'mode' : ModeSesi,
  'anggota' : Array<UserId>,
  'totalPoin' : bigint,
  'waktuMulai' : Timestamp,
  'puzzles' : Array<PuzzleId>,
  'indeksPuzzleAktif' : bigint,
  'namaTim' : [] | [string],
  'waktuSelesai' : [] | [Timestamp],
  'jawabanPuzzles' : Array<JawabanPuzzle>,
}
export type SessionId = bigint;
export type StatusSesi = { 'aktif' : null } |
  { 'selesai' : null };
export type TeamCode = string;
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'bergabungSesiTim' : ActorMethod<[TeamCode], [] | [SessionId]>,
  'buatSesiSolo' : ActorMethod<[], SessionId>,
  'buatSesiTim' : ActorMethod<[], [SessionId, TeamCode]>,
  'daftarkanNama' : ActorMethod<[string, SessionId, [] | [string]], undefined>,
  'getCityQuestion' : ActorMethod<[bigint], [] | [CityQuestion]>,
  'getLeaderboard' : ActorMethod<[], Array<EntriLeaderboard>>,
  'getPoinKumulatif' : ActorMethod<[], bigint>,
  'getPoinSesi' : ActorMethod<[SessionId], bigint>,
  'getPuzzle' : ActorMethod<[PuzzleId], [] | [Puzzle]>,
  'getRiwayatSesi' : ActorMethod<[], Array<RiwayatSesi>>,
  'getSesi' : ActorMethod<[SessionId], [] | [Sesi]>,
  'puzzleByKesulitan' : ActorMethod<[Difficulty], Array<Puzzle>>,
  'semuaCityQuestions' : ActorMethod<[], Array<CityQuestion>>,
  'semuaPuzzle' : ActorMethod<[], Array<Puzzle>>,
  'setNamaTim' : ActorMethod<[SessionId, string], boolean>,
  'submitJawaban' : ActorMethod<[SessionId, PuzzleId, bigint], HasilJawaban>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];