/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface JawabanPuzzle {
    sudahDievaluasi: boolean;
    poinTim: bigint;
    puzzleId: PuzzleId;
    waktuMulai: Timestamp;
    jawabanAnggota: Array<JawabanAnggota>;
}
export type Timestamp = bigint;
export interface EntriLeaderboard {
    namaPemain: string;
    userId: UserId;
    totalPoin: bigint;
    jumlahPermainan: bigint;
}
export type SessionId = bigint;
export type PuzzleId = bigint;
export interface HasilJawaban {
    poinTim?: bigint;
    poinDiperoleh: bigint;
    semuaSudahJawab: boolean;
    benar: boolean;
    penjelasan: string;
}
export type UserId = Principal;
export interface JawabanAnggota {
    userId: UserId;
    poinDiperoleh: bigint;
    pilihanJawaban: bigint;
    waktuSubmit: Timestamp;
    benar: boolean;
}
export type TeamCode = string;
export interface Puzzle {
    id: PuzzleId;
    pertanyaan: string;
    jawabanBenar: bigint;
    poinDasar: bigint;
    batasWaktu: bigint;
    pilihan: Array<string>;
    kesulitan: Difficulty;
    penjelasan: string;
}
export interface CityQuestion {
    id: bigint;
    gambar1: string;
    gambar2: string;
    poinDasar: bigint;
    batasWaktu: bigint;
    pilihan: Array<string>;
    namaKota: string;
    penjelasan: string;
}
export interface Sesi {
    id: SessionId;
    status: StatusSesi;
    kodeJoin?: string;
    mode: ModeSesi;
    anggota: Array<UserId>;
    totalPoin: bigint;
    waktuMulai: Timestamp;
    puzzles: Array<PuzzleId>;
    indeksPuzzleAktif: bigint;
    waktuSelesai?: Timestamp;
    jawabanPuzzles: Array<JawabanPuzzle>;
}
export interface RiwayatSesi {
    akurasi: bigint;
    tanggal: Timestamp;
    mode: string;
    poin: bigint;
    sessionId: SessionId;
}
export enum Difficulty {
    mudah = "mudah",
    sedang = "sedang",
    sulit = "sulit"
}
export enum ModeSesi {
    tim = "tim",
    solo = "solo"
}
export enum StatusSesi {
    aktif = "aktif",
    selesai = "selesai"
}
export interface backendInterface {
    bergabungSesiTim(kode: TeamCode): Promise<SessionId | null>;
    buatSesiSolo(): Promise<SessionId>;
    buatSesiTim(): Promise<[SessionId, TeamCode]>;
    daftarkanNama(namaPemain: string, sessionId: SessionId): Promise<void>;
    getCityQuestion(id: bigint): Promise<CityQuestion | null>;
    getLeaderboard(): Promise<Array<EntriLeaderboard>>;
    getPoinKumulatif(): Promise<bigint>;
    getPoinSesi(sessionId: SessionId): Promise<bigint>;
    getPuzzle(id: PuzzleId): Promise<Puzzle | null>;
    getRiwayatSesi(): Promise<Array<RiwayatSesi>>;
    getSesi(sessionId: SessionId): Promise<Sesi | null>;
    puzzleByKesulitan(kesulitan: Difficulty): Promise<Array<Puzzle>>;
    semuaCityQuestions(): Promise<Array<CityQuestion>>;
    semuaPuzzle(): Promise<Array<Puzzle>>;
    submitJawaban(sessionId: SessionId, puzzleId: PuzzleId, pilihanJawaban: bigint): Promise<HasilJawaban>;
}
import type { CityQuestion as _CityQuestion, Difficulty as _Difficulty, HasilJawaban as _HasilJawaban, JawabanPuzzle as _JawabanPuzzle, ModeSesi as _ModeSesi, Puzzle as _Puzzle, PuzzleId as _PuzzleId, Sesi as _Sesi, SessionId as _SessionId, StatusSesi as _StatusSesi, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bergabungSesiTim(arg0: TeamCode): Promise<SessionId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.bergabungSesiTim(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bergabungSesiTim(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async buatSesiSolo(): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.buatSesiSolo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buatSesiSolo();
            return result;
        }
    }
    async buatSesiTim(): Promise<[SessionId, TeamCode]> {
        if (this.processError) {
            try {
                const result = await this.actor.buatSesiTim();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buatSesiTim();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async daftarkanNama(arg0: string, arg1: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.daftarkanNama(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daftarkanNama(arg0, arg1);
            return result;
        }
    }
    async getCityQuestion(arg0: bigint): Promise<CityQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityQuestion(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityQuestion(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<EntriLeaderboard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getPoinKumulatif(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoinKumulatif();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoinKumulatif();
            return result;
        }
    }
    async getPoinSesi(arg0: SessionId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoinSesi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoinSesi(arg0);
            return result;
        }
    }
    async getPuzzle(arg0: PuzzleId): Promise<Puzzle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPuzzle(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPuzzle(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiwayatSesi(): Promise<Array<RiwayatSesi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiwayatSesi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiwayatSesi();
            return result;
        }
    }
    async getSesi(arg0: SessionId): Promise<Sesi | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSesi(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSesi(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async puzzleByKesulitan(arg0: Difficulty): Promise<Array<Puzzle>> {
        if (this.processError) {
            try {
                const result = await this.actor.puzzleByKesulitan(to_candid_Difficulty_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.puzzleByKesulitan(to_candid_Difficulty_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async semuaCityQuestions(): Promise<Array<CityQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.semuaCityQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.semuaCityQuestions();
            return result;
        }
    }
    async semuaPuzzle(): Promise<Array<Puzzle>> {
        if (this.processError) {
            try {
                const result = await this.actor.semuaPuzzle();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.semuaPuzzle();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitJawaban(arg0: SessionId, arg1: PuzzleId, arg2: bigint): Promise<HasilJawaban> {
        if (this.processError) {
            try {
                const result = await this.actor.submitJawaban(arg0, arg1, arg2);
                return from_candid_HasilJawaban_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitJawaban(arg0, arg1, arg2);
            return from_candid_HasilJawaban_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Difficulty_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_HasilJawaban_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HasilJawaban): HasilJawaban {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ModeSesi_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModeSesi): ModeSesi {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Puzzle_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Puzzle): Puzzle {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Sesi_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sesi): Sesi {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StatusSesi_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusSesi): StatusSesi {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionId]): SessionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CityQuestion]): CityQuestion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Puzzle]): Puzzle | null {
    return value.length === 0 ? null : from_candid_Puzzle_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sesi]): Sesi | null {
    return value.length === 0 ? null : from_candid_Sesi_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    status: _StatusSesi;
    kodeJoin: [] | [string];
    mode: _ModeSesi;
    anggota: Array<_UserId>;
    totalPoin: bigint;
    waktuMulai: _Timestamp;
    puzzles: Array<_PuzzleId>;
    indeksPuzzleAktif: bigint;
    waktuSelesai: [] | [_Timestamp];
    jawabanPuzzles: Array<_JawabanPuzzle>;
}): {
    id: SessionId;
    status: StatusSesi;
    kodeJoin?: string;
    mode: ModeSesi;
    anggota: Array<UserId>;
    totalPoin: bigint;
    waktuMulai: Timestamp;
    puzzles: Array<PuzzleId>;
    indeksPuzzleAktif: bigint;
    waktuSelesai?: Timestamp;
    jawabanPuzzles: Array<JawabanPuzzle>;
} {
    return {
        id: value.id,
        status: from_candid_StatusSesi_n11(_uploadFile, _downloadFile, value.status),
        kodeJoin: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.kodeJoin)),
        mode: from_candid_ModeSesi_n14(_uploadFile, _downloadFile, value.mode),
        anggota: value.anggota,
        totalPoin: value.totalPoin,
        waktuMulai: value.waktuMulai,
        puzzles: value.puzzles,
        indeksPuzzleAktif: value.indeksPuzzleAktif,
        waktuSelesai: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.waktuSelesai)),
        jawabanPuzzles: value.jawabanPuzzles
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    poinTim: [] | [bigint];
    poinDiperoleh: bigint;
    semuaSudahJawab: boolean;
    benar: boolean;
    penjelasan: string;
}): {
    poinTim?: bigint;
    poinDiperoleh: bigint;
    semuaSudahJawab: boolean;
    benar: boolean;
    penjelasan: string;
} {
    return {
        poinTim: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.poinTim)),
        poinDiperoleh: value.poinDiperoleh,
        semuaSudahJawab: value.semuaSudahJawab,
        benar: value.benar,
        penjelasan: value.penjelasan
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PuzzleId;
    pertanyaan: string;
    jawabanBenar: bigint;
    poinDasar: bigint;
    batasWaktu: bigint;
    pilihan: Array<string>;
    kesulitan: _Difficulty;
    penjelasan: string;
}): {
    id: PuzzleId;
    pertanyaan: string;
    jawabanBenar: bigint;
    poinDasar: bigint;
    batasWaktu: bigint;
    pilihan: Array<string>;
    kesulitan: Difficulty;
    penjelasan: string;
} {
    return {
        id: value.id,
        pertanyaan: value.pertanyaan,
        jawabanBenar: value.jawabanBenar,
        poinDasar: value.poinDasar,
        batasWaktu: value.batasWaktu,
        pilihan: value.pilihan,
        kesulitan: from_candid_Difficulty_n6(_uploadFile, _downloadFile, value.kesulitan),
        penjelasan: value.penjelasan
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aktif: null;
} | {
    selesai: null;
}): StatusSesi {
    return "aktif" in value ? StatusSesi.aktif : "selesai" in value ? StatusSesi.selesai : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tim: null;
} | {
    solo: null;
}): ModeSesi {
    return "tim" in value ? ModeSesi.tim : "solo" in value ? ModeSesi.solo : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mudah: null;
} | {
    sedang: null;
} | {
    sulit: null;
}): Difficulty {
    return "mudah" in value ? Difficulty.mudah : "sedang" in value ? Difficulty.sedang : "sulit" in value ? Difficulty.sulit : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Puzzle>): Array<Puzzle> {
    return value.map((x)=>from_candid_Puzzle_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    mudah: null;
} | {
    sedang: null;
} | {
    sulit: null;
} {
    return value == Difficulty.mudah ? {
        mudah: null
    } : value == Difficulty.sedang ? {
        sedang: null
    } : value == Difficulty.sulit ? {
        sulit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
